### PR TITLE
tmz 3.1.0 feature ieee754 converter binary float

### PR DESCRIPTION
**Pull request by t-m-z**

### CODE REVIEW

**Comment by S-Man42** [comment]
I am not quite sure, are some of your tests for cases that cannot precisely expressed ("double ungenauigkeit")? Like 0.2?

**Comment by S-Man42** [comment]
Any answer here?

**Comment by t-m-z** [comment]
Not yet. Still on holiday 

Sent from MailDroid

-----Original Message-----

**Comment by t-m-z** [comment]
check test and add one for 0.2

used 
https://zahlensysteme-rechner.de/ieee-754-konverter/
https://www.h-schmidt.net/FloatConverter/IEEE754.html
to validate

**Pull request merged**
