### PR TITLE
tmz 2.0.0 Piano key frequences #271

### PR DESCRIPTION
**Pull request by t-m-z**
just for discussion

### CODE REVIEW

**Comment by S-Man42** [comment]
Without seeing your work: My intension was doing it exactly like the zodiac tool...

**Comment by t-m-z** [comment]
This answers my question .
As soon as I saw the result of my work I was sure there should be a better solution.

**Comment by S-Man42** [comment]
:D

Sry for being not more constructive... Just wanted to say what was in my mind. I am still not home, couldnt have a look at your solution. So, maybe yours is good or even better - you must decide :)

**Comment by t-m-z** [comment]
No it is okay - as I wrote: I saw my result and was sure, that is hitting the dart board but not bulls eye.
If I had seen your Zodiac earlier I would have chosen this UI. 
So do not waste your time I will come back

**Comment by t-m-z** [comment]
second try    ;-)

**Pull request merged**
