### PR TITLE
add default padding for every call of GCWSegmentDisplay as a workaround

### PR DESCRIPTION
**Pull request by t-m-z**
horizontalSymbolPadding: 5,
        verticalSymbolPadding: 5,

### CODE REVIEW

**Comment by S-Man42** [comment]
No, to avoid multiple default values all. over the app, the right place for this would be the constructor of the GCWSegmentDisplayDingens

**Comment by t-m-z** [comment]
Hm. Okay. But then I have no clue how to do this the right way. 
There is a widget.horizontalPadding which does not work properly. So I thought to set the data explicitly.


Sent from MailDroid

-----Original Message-----

**Comment by S-Man42** [comment]
```
const GCWSegmentDisplayOutput(
      {Key key,
      this.upsideDownButton: false,
      this.segmentFunction,
      this.segments,
      this.readOnly,
      this.trailing,
      this.showZoomButtons: true,
      this.verticalSymbolPadding: 5,
      this.horizontalSymbolPadding: 5})
      : super(key: key);
```

This does not work?

**Comment by Mike-3** [comment]
This fix works on my short test

  const GCWSegmentDisplayOutput(
      {Key key,
      this.upsideDownButton: false,
      this.segmentFunction,
      this.segments,
      this.readOnly,
      this.trailing,
      this.showZoomButtons: true,
      this.verticalSymbolPadding = 5.0,
      this.horizontalSymbolPadding = 5.0})
      : super(key: key);

  @override
  _GCWSegmentDisplayOutputState createState() => _GCWSegmentDisplayOutputState();
}

**Comment by t-m-z** [comment]
unfortunately not

Sent from MailDroid

-----Original Message-----

**Pull request closed without merging**
