### PR TITLE
Multi decoder esoteric languages

### PR DESCRIPTION
**Pull request by Mike-3**
tool for Deadfish
tool for Chef
tool for Beatnik
tool for other languages

### CODE REVIEW

**Comment by S-Man42** [comment]
I find it very confusing: We have 

- Beatnik
- Chef
- Deadfish
- and Esoteric Languages...

I guess it makes more sense to add all (main) esoteric languages into the main menu (not the bf derivates). But all Brainfk derivates as selection to brainfk.

Additionally: When you already work on this: Please add the new Pokémon Code as well! :)

**Comment by Mike-3** [comment]
changed

**Comment by S-Man42** [comment]
Oh, sorry. I believe you misunderstood. I would not split "BrainFk" and "BrainFk Derivates". Could you please put them together. And as default setting "Brainfk" (the normal one...). Could you please change this? :)

**Comment by S-Man42** [comment]
Hohoho is not handled as a bf derivate but a separate language. Please move it from the bf derivates :)

**Comment by t-m-z** [comment]
removed Hohoho from brainfk_trivialsubstitutions

**Pull request merged**
