### PR TITLE
Substitution: Generate random substitutions

### LINKED ISSUE #1681: Textersetzung: Random encryption

### PR DESCRIPTION
**Pull request by S-Man42**
closes #1681

### CODE REVIEW

**Review by Mike-3 — APPROVED** [review]

**Comment by Mike-3** [comment]
I just noticed that if I press it multiple times, the block keeps getting appended. Is that intentional?

**Comment by Mike-3** [comment]
If possible, add tests.

**Comment by S-Man42** [comment]
> If possible, add tests.

Hm, hard to add tests on a frontend function and hard to add test on a totally random result... No I believe, here it makes no sense, since it is not lart of the logic but only an enhancement of the input UI

**Comment by Mike-3** [comment]
I didn't even notice it at first because the new entries were outside of my field of vision.

**Pull request merged**
