### PR TITLE
Loading image in exif

### PR DESCRIPTION
**Pull request by ludoo0d0a**
add loader
format date according to locale

### CODE REVIEW

**Comment by ludoo0d0a** [comment]
#600

**Comment by S-Man42** [comment]
Why do you don't take the already existing ProgressIndicator? From my point of view, the app should be consistent across all tools...

**Comment by S-Man42** [comment]
Is there still progress?

**Comment by S-Man42** [comment]
Do you have an idea, how the get the many additional information out of this image as exif online does: Lens information and so on...

https://s-man42.de/salat.jpg

Exif Online Output:

<html><body>
<p style="margin-top:40px; margin-bottom:0"><b><big id="XMP">XMP</big></b></p>

Date Created | 2007:11:27 15:36:1313 years, 7 months, 20 days, 13 hours, 10 minutes, 27 seconds ago
-- | --
XMP Toolkit | Adobe XMP Core 5.3-c011 66.145661, 2012/02/06-14:56:27
Serial Number | 330113594
Lens Info | 60mm f/?
Lens | EF-S60mm f/2.8 Macro USM
Lens ID | 236
Image Number | 0
Approximate Focus Distance | 0.32
Flash Compensation | 0
Firmware | 1.0.3
Modify Date | 2014:02:05 19:41:51+01:007 years, 5 months, 12 days, 17 hours, 4 minutes, 49 seconds ago
Metadata Date | 2014:02:05 19:41:51+01:007 years, 5 months, 12 days, 17 hours, 4 minutes, 49 seconds ago
Color Mode | RGB
ICC Profile Name | sRGB IEC61966-2.1
Document ID | B57E1B62CDB200F5990EC3B64CAEB5EE
Instance ID | xmp.iid:23AE56E8938EE311AEC881043534D176
Original Document ID | B57E1B62CDB200F5990EC3B64CAEB5EE
Format | image/jpeg
History Action | saved
History Instance ID | xmp.iid:23AE56E8938EE311AEC881043534D176
History When | 2014:02:05 19:41:51+01:007 years, 5 months, 12 days, 17 hours, 4 minutes, 49 seconds ago
History Software Agent | Adobe Photoshop CS6 (Windows)
History Changed | /


</body>
</html>

**Comment by S-Man42** [comment]
I checked the above mentioned image now directly from the new URL loader:

Field XP Comment should be decoded

grafik

**Comment by S-Man42** [comment]
Closed by #633 653

**Pull request merged**
