### PR TITLE
Whitespace language

### PR DESCRIPTION
**Pull request by Mike-3**

### CODE REVIEW

**Comment by S-Man42** [comment]
Generator: 
* Input Text: "Blablubb" -> Output only 2 Spaces... I guess, that's wrong. 
* Add a readable output. I think, that would make more sense.

Interpreter:
* This example seems not working: https://www.whoishostingthis.com/resources/whitespace-programming/ Expected output is 12345, actual output is 1
* How does it behave (like the given example) if a readable form contains whitespace? Will it take the readable form or the whitespace? Same issues is here: https://de.wikipedia.org/wiki/Whitespace_(Programmiersprache)
* Please don't show a Divider, if nothing is below this. My first try showed an empty "Info" section. After switching the modes there and back, it showed the complete output section.

**Comment by S-Man42** [comment]
Working:
* http://progopedia.com/language/whitespace/
* https://h0tsh0tt.wordpress.com/2016/07/03/whitespace-language-tutorial/

Not working:
* https://esolangs.org/wiki/Whitespace
* Unfortunately the most important reference: https://web.archive.org/web/20180121144154/http://99-bottles-of-beer.net/language-whitespace-154.html

**Comment by Mike-3** [comment]
Not working problem:
- This example seems not working: https://www.whoishostingthis.com/resources/whitespace-programming/ Expected output is 12345, actual output is 1
> Test with other online Interpreter -> output also 1
I think the program ist not correct.

- Unfortunately the most important reference: https://web.archive.org/web/20180121144154/http://99-bottles-of-beer.net/language-whitespace-154.html
> Test with other online Interpreter -> no output 

- https://web.archive.org/web/20150717115008/http://compsoc.dur.ac.uk/whitespace/examples.php
> Hello, user:  woks only with interpreter https://www.dcode.fr/whitespace-language
> Hello, Calculator:  woks only with interpreter https://www.dcode.fr/whitespace-language


tested with
http://kryptografie.de/kryptografie/chiffre/whitespace.htm
https://naokikp.github.io/wsi/whitespace.html
https://www.dcode.fr/whitespace-language

- https://esolangs.org/wiki/Whitespace
> The detection can be expanded to include these markers ([Tab][Space][LF])

**Comment by Mike-3** [comment]
"Info" section removed. input dialog added.

Now working:
** Hello, user: Asks for name, but not continue
** Calculator: Asks for number, but after entering "1234" the program run very long and ented with crucial output

**Comment by S-Man42** [comment]
Concerning https://github.com/S-Man42/GCWizard/pull/268#issuecomment-738112119
Unchanged behaviour for generator: 
* Unbelievable short output for input "blablubb"
* No readable output line
* Decoder: Please show output widget only if there's any output. Currently the divider appears at onChanged of input field, not at onPressed of button

On the other hand: Wiki example works right now. Maybe "Readble Code" should only be shown if input code is not readable?

**Comment by S-Man42** [comment]
The dialog function is not working for me. I tried all the tests from https://web.archive.org/web/20150717115008/http://compsoc.dur.ac.uk/whitespace/examples.php but after clicking on "Start" nothing happens.

**Comment by Mike-3** [comment]
Unbelievable short output for input "blablubb"
    No readable output line
-> thats correct
Encoder -> visible Text to WhiheSpace
Decoder -> Whitespace to visible Text

    Decoder: Please show output widget only if there's any output. Currently the divider appears at onChanged of input field, not at onPressed of button; I'd do it that way: Remove at onChanged, Show at onPressed
-> I do not understand. There is no longer an input field

**Comment by Mike-3** [comment]
The dialog function is not working for me. I tried all the tests from https://web.archive.org/web/20150717115008/http://compsoc.dur.ac.uk/whitespace/examples.php but after clicking on "Start" nothing happens.
[fibonacci.ws.txt](https://github.com/S-Man42/GCWizard/files/5703668/fibonacci.ws.txt)
[hanoi.ws.txt](https://github.com/S-Man42/GCWizard/files/5703669/hanoi.ws.txt)
[fact.ws.txt](https://github.com/S-Man42/GCWizard/files/5703670/fact.ws.txt)
[calc.ws.txt](https://github.com/S-Man42/GCWizard/files/5703671/calc.ws.txt)

-> all work
[name.ws.txt](https://github.com/S-Man42/GCWizard/files/5703667/name.ws.txt)

**Pull request merged**
