### PR TITLE
tmz 3.0.0 symbol sith

### PR DESCRIPTION
**Pull request by t-m-z**
user wish via whatapp -  https://www.geocaching.com/geocache/GCA9PBW_wanted-der-auftrag
CDJ 2023 - Berlin   ;-)

### CODE REVIEW

**Comment by S-Man42** [comment]
Hm, here the translation files shouldnt be included. That could yield conflicts.

**Comment by t-m-z** [comment]
The translation files were downloaded accidentally. I think they will not cause conflicts as far as I understand this crowdin tool.
The only files which were uploaded are the english sources. The translations should only be downloaded and therefore overwritten.

**Comment by S-Man42** [comment]
Please remove the translations files here as well... So see the potential conflicts: I'd merge these, then I download the actual translations from crowdin and from your next PR (ie. base16 tests) I get the translation files as well.. Git would create a conflict. DO NOT commit files which are not related to your feature!

**Comment by t-m-z** [comment]
Close, clean and restart

**Comment by t-m-z** [comment]
I have no clue how to remove these files from a comit. I will delete the whole bracnch and start again from scratch

**Pull request closed without merging**
