### PR TITLE
tmz 2.2.0 symbol morse

### PR DESCRIPTION
**Pull request by t-m-z**
add table

### CODE REVIEW

**Comment by S-Man42** [comment]
Maybe it makes sense to add a selection_morse here and adjust the searchstrings

**Comment by S-Man42** [comment]
Searchstring are good. But a selection could make sense nonetheless. Btw. why are "Brainfk" and "Ook" part of the result list when searching for "morse"? Maybe remove?

**Comment by t-m-z** [comment]
> Btw. why are "Brainfk" and "Ook" part of the result list when searching for "morse"? Maybe remove?

No - because we have a derivat named Morsef*ck

**Comment by t-m-z** [comment]
add selection - but I am lost.
Also the selection has no searchKey, it will be shown when searching Morse - I mixed something, but what?

**Comment by S-Man42** [comment]
aaaaah that could be my own fault... i enhanced the search: next to normal searchnstring, it checks the titles of a tool (idea is to provide search support even if the search strings are not yet translated)... aaargh.. i guess i need to dive into this.

**Pull request merged**
