### PR TITLE
book cipher extension

### PR DESCRIPTION
**Pull request by Mike-3**

### CODE REVIEW

**Comment by S-Man42** [comment]
grafik

The "Mode" under "Spaces": Is it "empty lines"? or "ignore symbols"? or...

I'd make Spaces and Empty lines "off" by default. I recently had to deal with several book ciphers... All had spaces and empty lines off (only one, which explicitly mentioned, to recognizes spaces as well).

For "ignore symbols" i'd make a switch as well. So you can disable the ignoring without clearing the entire text field...

**Comment by S-Man42** [comment]
Maybe "only first word letter" not under "advanced" but as general option?

**Comment by Mike-3** [comment]
The "Mode" under "Spaces": Is it "empty lines"? or "ignore symbols"? or...
fixed

So until now I had almost only book cipher, where line-word-letter was given. So if you deactivate spaces, you can no longer determine a word. Then just every line would be a new word.
But I disable it by default.

**Comment by Mike-3** [comment]
book_chipher

ok ?

**Comment by S-Man42** [comment]
Yes, not all combinations make sense at all, of course... I guess that will do the job, I'll test it.

**Comment by S-Man42** [comment]
Do you mind the conflicts?

**Pull request merged**
