### PR TITLE
Tmz 2.1.0 iata icao

### PR DESCRIPTION
**Pull request by t-m-z**
Your country codes were an inspiration. The data is copied from https://airportcodes.aero/ 

However, there is still something to do - but I have no idea how to integrate this rolling donut to show that something is going 
on.

### CODE REVIEW

**Comment by t-m-z** [comment]
Rready for review
Regarding the full view, someone has to implement these "waiting feature". I have no clue how to build these async stuff :-(

**Comment by S-Man42** [comment]
First try: Entered "TXL" into IATA search: Red Screen of Death

```
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building IATAICAOSearch(dirty, dependencies: [_LocalizationsScope-[GlobalKey#785a3]], state: IATAICAOSearchState#3f175):
type 'List<List<dynamic>>' is not a subtype of type 'List<List<String>>'

The relevant error-causing widget was: 
  IATAICAOSearch file:///E:/workspace/GCWizard/lib/widgets/registry.dart:3812:15
When the exception was thrown, this was the stack: 
#0      IATAICAOSearchState._buildOutput (package:gc_wizard/widgets/tools/science_and_technology/iata_icao/iata_icao_search.dart:98:7)
#1      IATAICAOSearchState.build (package:gc_wizard/widgets/tools/science_and_technology/iata_icao/iata_icao_search.dart:67:33)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
...
====================================================================================================
```

**Comment by S-Man42** [comment]
I'd really remove the "List all" feature... That really takes very long to be opened and it's quite hard to find anything in it with scrolling that much entries - escpecially bc scrolling takes much much time.

**Comment by t-m-z** [comment]
> I'd really remove the "List all" feature... That really takes very long to be opened and it's quite hard to find anything in it with scrolling that much entries - escpecially bc scrolling takes much much time.

I understand that point of view - however I wouls still stick to it. But implement this async rolling circle.

**Comment by t-m-z** [comment]
> First try: Entered "TXL" into IATA search: Red Screen of Death
> 
> ```
> ======== Exception caught by widgets library =======================================================
> The following _TypeError was thrown building IATAICAOSearch(dirty, dependencies: [_LocalizationsScope-[GlobalKey#785a3]], state: IATAICAOSearchState#3f175):
> type 'List<List<dynamic>>' is not a subtype of type 'List<List<String>>'
> 
> The relevant error-causing widget was: 
>   IATAICAOSearch file:///E:/workspace/GCWizard/lib/widgets/registry.dart:3812:15
> When the exception was thrown, this was the stack: 
> #0      IATAICAOSearchState._buildOutput (package:gc_wizard/widgets/tools/science_and_technology/iata_icao/iata_icao_search.dart:98:7)
> #1      IATAICAOSearchState.build (package:gc_wizard/widgets/tools/science_and_technology/iata_icao/iata_icao_search.dart:67:33)
> #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
> #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
> #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
> ...
> ====================================================================================================
> ```

found a solution - but do not realy know the background

**Comment by S-Man42** [comment]
> 
> 
> > I'd really remove the "List all" feature... That really takes very long to be opened and it's quite hard to find anything in it with scrolling that much entries - escpecially bc scrolling takes much much time.
> 
> I understand that point of view - however I wouls still stick to it. But implement this async rolling circle.

That would be a task for @Mike-3. However... here we have complete different views. I don't understand how someone should use the tool. Is there an option to sort the column or something? So, otherwise you must read every data set to find you IATA code.. You are not even able to search for let's say "Berlin" because the name of the airport is ordered, not the city... I would always use the search engine... Maybe I didn't understand the use case? :)

**Comment by t-m-z** [comment]
> > > I'd really remove the "List all" feature... That really takes very long to be opened and it's quite hard to find anything in it with scrolling that much entries - escpecially bc scrolling takes much much time.
> > 
> > 
> > I understand that point of view - however I wouls still stick to it. But implement this async rolling circle.
> 
> That would be a task for @Mike-3. However... here we have complete different views. I don't understand how someone should use the tool. Is there an option to sort the column or something? So, otherwise you must read every data set to find you IATA code.. You are not even able to search for let's say "Berlin" because the name of the airport is ordered, not the city... I would always use the search engine... Maybe I didn't understand the use case? :)

hm - there is an option in the List to sorty ba IATA, ICAO or Name. The main ide was to give an overview. But you are right, this is a question of performance.
With the Search toll - you can get also an overview letterwise - but I would the suggest to add another switch to toggle between IATA and ICAO to decreas the number of entries.

**Comment by S-Man42** [comment]
Maybe a dropdown: "Search by"

"Name" -> Search entire string (`listElement.contains(input)`)
"IATA and ICAO" (if user is not quite sure), but only with beginning (`listElement.startsWith(input)`)
"IATA" (also `startsWith`)
"ICAO" (also `startsWith`)

**Comment by t-m-z** [comment]
removed the selection
added a 2nd switch to differ between IATA and ICAO - it seems that this improves the performance

**Comment by S-Man42** [comment]
Merged with #659

**Pull request merged**
