### PR TITLE
TMZ      2.2.0     add symbol table Ninjagon

### PR DESCRIPTION
**Pull request by t-m-z**

### CODE REVIEW

**Comment by S-Man42** [comment]
Waiting for @Birdy2404 . He wants to check the licenses..... Lego is not the good guy when it comes to copyright issues...

**Comment by t-m-z** [comment]
I now. I made this experience when publishing the Besondere Lernleistung of my sin Jann-Niklas.
Over all it is a question of the correct naming - using the Trademark Symbol together with LEGO and Ninjago and writing a disclaimer in the Licence section.

Sent from MailDroid

-----Original Message-----

**Comment by Birdy2404** [comment]
New symbols from the ttf are created and stored in the Exchangefolder
...\Exchange\Symboltabellen\Ninjagon

**Comment by t-m-z** [comment]
Symbols improved by Andy/Birdy2404

**Pull request merged**
