### PR TITLE
Symbol tables handling/resized

### PR DESCRIPTION
**Pull request by Mike-3**
symbol_tables zipped (first zip-file in the folder used )
config.json and preview image not zipped
color depth redused

### CODE REVIEW

**Comment by S-Man42** [comment]
Please resolve conflicts

**Comment by S-Man42** [comment]
Greate work so far (about the problems with web I told you via messenger).

Should be merged with #356 to avoid any conflicts

**Comment by S-Man42** [comment]
One idea: We should make the "logo" symbol always named "logo.png". So, we can remove this line from the registry.

**Comment by Mike-3** [comment]
I rename all logo symbols and change the registry and code.

**Pull request merged**
