### PR TITLE
Update notes segmentdisplay

### PR DESCRIPTION
**Pull request by Mike-3**

### CODE REVIEW

**Comment by S-Man42** [comment]
Is it possible to create an output without gaps here? And maybe thinner symbols (without that much empty line space around).

So that would create something which looks more like a real note sheet, not just some lonely note symbols. I guess that would be a great preparation for a potential output of this one here: #828

**Comment by S-Man42** [comment]
Update: Part 1: No symbol spaces:

grafik

Todo: Thinner segment display output symbols...

**Comment by S-Man42** [comment]
Tadaaa...

grafik

**Comment by S-Man42** [comment]
Now missing for entire perfection: The chosen note clef (violin, alt, bass) always at the beginning.

**Comment by Mike-3** [comment]
Very nice. Have you a example with b or #.

**Comment by S-Man42** [comment]
Have look at the last both. or what do you mean

**Pull request merged**
