### PR TITLE
Issue open map import kml/kmz/gpx

### PR DESCRIPTION
**Pull request by Mike-3**
restore circles
with file picker
open file_picker with longPress on paste-button (Open Map)  (tested with web)

### CODE REVIEW

**Comment by S-Man42** [comment]
As mentioned on phone: I#d go with Icons.drive_folder_upload

**Comment by S-Man42** [comment]
We now have some conflicts here. Please check :)

**Comment by Mike-3** [comment]
Seperate import Button
grafik

**Comment by Mike-3** [comment]
grafik
better ?

**Pull request merged**
