### PR TITLE
hidden data file type extension

### PR DESCRIPTION
**Pull request by Mike-3**
add bmp, zip, rar, mp3

### CODE REVIEW

**Comment by S-Man42** [comment]
When trying the recursive example (bg.jpg -> lat.mp3 -> text) from https://s-man42.de/bg.jpg in Exif Tool, I get a

NullPointerException:
```

======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building ExifReader(dirty, dependencies: [_LocalizationsScope-[GlobalKey#715e7]], state: _ExifReaderState#9d351):
The method '>' was called on null.
Receiver: null
Tried calling: >(0)

The relevant error-causing widget was: 
  ExifReader file:///E:/workspace/GCWizard/lib/widgets/registry.dart:807:21
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      extraData (package:gc_wizard/logic/tools/images_and_files/hidden_data.dart:35:44)
#2      extraData (package:gc_wizard/logic/tools/images_and_files/hidden_data.dart:41:18)
#3      _ExifReaderState._decorateExtraData (package:gc_wizard/widgets/tools/images_and_files/exif_reader.dart:249:22)
#4      _ExifReaderState._buildOutput (package:gc_wizard/widgets/tools/images_and_files/exif_reader.dart:109:5)
...
====================================================================================================

```

**Comment by S-Man42** [comment]
Great.

Well, in Exif viewer now the output is not recursive:

Zip -> content
-> lat.mp3

(missing something like 
-> lat.map -> content
-> lon.txt (or whatever it is called)
)

Is it intended?

**Comment by S-Man42** [comment]
Take an invalid URL, like this:
sadjk.com/bla.gif

For any reason, that returns a Status 200, which is ok. But nonetheless, this is giving no return.

You hidden data routing throws an exception, when opening this url in Exif Viewer...

After opening a file, we MUST check for validity directly afterwards... E.g. in Animated tool: Is the file really a GIF/PNG/whatever file...

**Comment by Mike-3** [comment]
In the animated tool is a file type check.

**Comment by S-Man42** [comment]
OK, added checks for Exif and ColorCorrections: https://github.com/S-Man42/GCWizard/commit/35930e20ec50046e63e170059bbd5084d838108f

Could you please check for the other tools? Please add a 

`showToast('my_message_string');`

as well, if there are any problems. It's better than just show nothing as I did here:

https://github.com/S-Man42/GCWizard/commit/35930e20ec50046e63e170059bbd5084d838108f#diff-9196b1a918f20ec1b55e50dbe75bdd86ac479d7fe44f8a19f10c95d920f8019fR66

**Comment by Mike-3** [comment]
> Great.
> 
> Well, in Exif viewer now the output is not recursive:
> 
> Zip -> content
> -> lat.mp3
> 
> (missing something like
> -> lat.map -> content
> -> lon.txt (or whatever it is called)
> )
> 
> Is it intended? #
> 

I am not sure what you mean. 
In this case, the mp3 file is only available in the zip file. There is no other file, as far as I know, hidden.
Only a thumbnail is left of the mp3 file.

**Pull request merged**
