### PR TITLE
Tmz 3.0.0 enhance base64

### PR DESCRIPTION
**Pull request by t-m-z**
add feature to differ between text, image and sound base64 encoded data and show it

### CODE REVIEW

**Comment by S-Man42** [comment]
Could you please add a test?

**Comment by t-m-z** [comment]
added

**Comment by S-Man42** [comment]
We should definitely add a Waiting Spinner when input gets too long. My emulator froze at the first example I tried... a 316kb JPG, 1440x960px

**Comment by t-m-z** [comment]
AsyncExecuter added - but this will not solve the problm with the clipboard

**Pull request merged**
