### PR TITLE
MaterialPageRoute -> NoAnimationMaterialPageRoute

### PR DESCRIPTION
**Pull request by Mike-3**
null problem with clipboard editor persists

### CODE REVIEW

**Comment by S-Man42** [comment]
> null problem with clipboard editor persists

What does this mean. Does this break anything?

**Comment by S-Man42** [comment]
This does not affect the original ticket #1253 which is not about "MaterialPageRoute" but "NavigationService"

**Comment by Mike-3** [comment]
> What does this mean. Does this break anything?

No, everything is just the same as before.

**Comment by Mike-3** [comment]
> This does not affect the original ticket #1253 which is not about "MaterialPageRoute" but "NavigationService"

I thought that meant both

**Comment by S-Man42** [comment]
It's ok what you did, indeed. However, the more important one is the NavigationService which is used at one part instead of the RouteThing

**Pull request closed without merging**
